/**
 * EXPORT UI — Save/Load/Export/Example
 */
import { S, ROW_COUNTS } from '../state/state.js';
import { DEFS } from '../engine/componentDefs.js';
import { sc, sn, scolor, rr } from '../utils/helpers.js';
import { calculateMaturityMetrics, buildExecSummaryHTML } from './execSummary.js';
import { redraw } from './renderSVG.js';
import { createNode, makeDrag, clearCanvas } from './canvasUI.js';
import { goStep } from './scopeUI.js';
import { runAnalysis } from '../engine/threatEngine.js';
import { renderTrustZoneOverlays } from './trustZones.js';
import { zoomFit } from './zoomPan.js';
import { upHint } from '../utils/helpers.js';
import { selNode, handlePort } from './canvasUI.js';

function _readScopeTable(tbodyId) {
    const rows = [];
    document.getElementById(tbodyId).querySelectorAll('tr').forEach(tr => {
        const cells = [...tr.querySelectorAll('td')];
        if (!cells.length) return;
        const row = cells.slice(0, -1).map(td => { const sel = td.querySelector('select'); return sel ? sel.value : td.textContent.trim(); });
        rows.push(row);
    });
    return rows;
}

export function exportReport() {
    const name = document.getElementById('appName').value || 'Unnamed Application';
    const ver = document.getElementById('appVersion').value || '1.0';
    const desc = document.getElementById('appDesc').value || 'No description.';
    const owner = document.getElementById('docOwner').value || '—';
    const parts = document.getElementById('docParticipants').value || '—';
    const rev = document.getElementById('docReviewer').value || '—';
    const date = document.getElementById('docDate').value || new Date().toISOString().split('T')[0];
    const ord = { critical: 0, high: 1, medium: 2, low: 3 };
    const sorted = [...S.threats].sort((a, b) => ord[a.sev] - ord[b.sev]);
    const scl = s => ({ critical: '#dc2626', high: '#ea580c', medium: '#ca8a04', low: '#16a34a' }[s] || '#666');
    const execHtml = S.threats.length ? buildExecSummaryHTML(calculateMaturityMetrics(), true) : '';
    const html = `<!DOCTYPE html><html><head><meta charset="UTF-8"><title>Threat Model — ${name}</title>
<style>body{font-family:Arial,sans-serif;max-width:1100px;margin:40px auto;color:#222;line-height:1.6}h1{font-size:26px;border-bottom:3px solid #222;padding-bottom:8px}h2{font-size:17px;border-left:4px solid #0d6efd;padding-left:12px;margin-top:28px}table{width:100%;border-collapse:collapse;margin-top:10px;font-size:13px}th{background:#222;color:#fff;padding:8px 11px;text-align:left}td{padding:7px 11px;border-bottom:1px solid #ddd;vertical-align:top}tr:nth-child(even)td{background:#f8f9fa}.meta{display:grid;grid-template-columns:1fr 1fr;gap:8px 24px;background:#f8f9fa;padding:14px;border-radius:8px;font-size:13px}.meta label{font-weight:700;font-size:11px;display:block;text-transform:uppercase;color:#666}</style></head>
<body><h1>🛡 Threat Model Report</h1><p style="color:#666;margin-top:-4px">Generated by ThreatCanvas · OWASP Threat Modeling Process</p>
${execHtml}
<h2>1. Project Information</h2>
<div class="meta"><div><label>Application</label>${name} v${ver}</div><div><label>Date</label>${date}</div><div><label>Document Owner</label>${owner}</div><div><label>Participants</label>${parts}</div><div><label>Reviewer</label>${rev}</div><div><label>Threats Found</label>${S.threats.length}</div></div>
<div style="margin-top:10px;padding:10px 14px;background:#f8f9fa;border-radius:8px;font-size:13px"><strong>Description:</strong> ${desc}</div>
<h2>2. Architecture — DFD Components</h2>
<table><thead><tr><th>Component</th><th>Type</th><th>Trust Level</th></tr></thead><tbody>${Object.values(S.nodes).map(n => `<tr><td>${n.label}</td><td>${n.type}</td><td>${n.trust}</td></tr>`).join('')}</tbody></table>
<h2>3. Data Flows</h2>
<table><thead><tr><th>From</th><th>To</th><th>Protocol</th><th>Data Class</th><th>Auth</th><th>Encryption</th><th>Trust Boundary</th></tr></thead><tbody>${S.edges.map(e => `<tr><td>${S.nodes[e.from]?.label || e.from}</td><td>${S.nodes[e.to]?.label || e.to}</td><td>${e.protocol}</td><td>${e.dataClass}</td><td>${e.auth}</td><td>${e.encryption}</td><td>${e.trustBoundary}</td></tr>`).join('')}</tbody></table>
<h2>4. Threat List (STRIDE)</h2>
${!S.threats.length ? '<p>No threats detected.</p>' : `<table><thead><tr><th>ID</th><th>Threat</th><th>STRIDE</th><th>Severity</th><th>Likelihood</th><th>Impact</th><th>Risk</th><th>Response</th><th>Status</th></tr></thead><tbody>${sorted.map(t => { const row = S.cmRows[t.id] || { response: '—', status: 'Non-Mitigated' }; return `<tr><td>${t.id}</td><td>${t.name}</td><td>${sn(t.stride)}</td><td style="color:${scl(t.sev)};font-weight:700">${t.sev.toUpperCase()}</td><td>${t.like}</td><td>${t.imp}</td><td style="color:${scl(rr(t.like, t.imp).toLowerCase())};font-weight:700">${rr(t.like, t.imp)}</td><td>${row.response}</td><td>${row.status}</td></tr>`; }).join('')}</tbody></table>`}
<h2>5. Countermeasure Details</h2>
${sorted.map(t => `<div style="background:#f8f9fa;border-left:4px solid ${scl(t.sev)};padding:12px 14px;margin-bottom:12px;border-radius:0 8px 8px 0"><strong>${t.id}: ${t.name}</strong> <span style="font-size:12px;color:#666">— ${sn(t.stride)} · Control: ${t.ctrl}</span><p style="margin:7px 0;font-size:13px">${t.desc}</p><strong style="font-size:12px">Mitigations:</strong><ul style="margin:4px 0;font-size:13px">${t.mits.map(m => `<li>${m}</li>`).join('')}</ul></div>`).join('')}
<p style="margin-top:28px;font-size:11px;color:#999;border-top:1px solid #ddd;padding-top:10px">Generated ${new Date().toLocaleString()} · ThreatCanvas</p>
</body></html>`;
    const blob = new Blob([html], { type: 'text/html' }); const a = document.createElement('a'); a.href = URL.createObjectURL(blob); a.download = `threat-model-${name.replace(/\s+/g, '-').toLowerCase()}.html`; a.click();
}

export function saveProject() {
    const appName = document.getElementById('appName').value || 'Unnamed';
    const payload = {
        _tc: 'ThreatCanvas/2.0', savedAt: new Date().toISOString(),
        projectInfo: { appName: document.getElementById('appName').value, appVersion: document.getElementById('appVersion').value, appDesc: document.getElementById('appDesc').value, docOwner: document.getElementById('docOwner').value, docParticipants: document.getElementById('docParticipants').value, docReviewer: document.getElementById('docReviewer').value, docDate: document.getElementById('docDate').value },
        scopeTables: { trust: _readScopeTable('trustTbody'), entry: _readScopeTable('entryTbody'), exit: _readScopeTable('exitTbody'), assets: _readScopeTable('assetsTbody'), deps: _readScopeTable('depsTbody') },
        topology: { nodes: S.nodes, edges: S.edges.map(e => ({ ...e, _atk: false, _atkColor: null })), nextId: S.nextId },
        cmRows: S.cmRows,
    };
    const blob = new Blob([JSON.stringify(payload, null, 2)], { type: 'application/json' });
    const a = document.createElement('a'); a.href = URL.createObjectURL(blob); a.download = `threatcanvas-${appName.replace(/\s+/g, '-').toLowerCase()}-${new Date().toISOString().slice(0, 10)}.json`; a.click(); URL.revokeObjectURL(a.href);
    const btn = document.querySelector('.btn-save'); if (btn) { const orig = btn.textContent; btn.textContent = '✓ Saved!'; btn.style.color = '#00ff99'; setTimeout(() => { btn.textContent = orig; btn.style.color = ''; }, 1800); }
}

function _bTR(i, c) { return `<tr><td>TL-${i}</td><td contenteditable="true" style="outline:none;color:var(--text)">${c[1] || ''}</td><td contenteditable="true" style="outline:none;color:var(--text2)">${c[2] || ''}</td><td><button class="del-btn" onclick="this.closest('tr').remove()">✕</button></td></tr>`; }
function _bER(i, c) { return `<tr><td>EP-${i}</td><td contenteditable="true" style="outline:none;color:var(--text)">${c[1] || ''}</td><td contenteditable="true" style="outline:none;color:var(--text2)">${c[2] || ''}</td><td contenteditable="true" style="outline:none;color:var(--text2)">${c[3] || ''}</td><td><button class="del-btn" onclick="this.closest('tr').remove()">✕</button></td></tr>`; }
function _bXR(i, c) { const r = c[3] || 'Medium'; return `<tr><td>XP-${i}</td><td contenteditable="true" style="outline:none;color:var(--text)">${c[1] || ''}</td><td contenteditable="true" style="outline:none;color:var(--text2)">${c[2] || ''}</td><td><select style="background:var(--s2);border:1px solid var(--border);border-radius:4px;color:var(--text);font-size:11px;padding:2px"><option ${r === 'High' ? 'selected' : ''}>High</option><option ${r === 'Medium' ? 'selected' : ''}>Medium</option><option ${r === 'Low' ? 'selected' : ''}>Low</option></select></td><td><button class="del-btn" onclick="this.closest('tr').remove()">✕</button></td></tr>`; }
function _bAR(i, c) { return `<tr><td>A-${i}</td><td contenteditable="true" style="outline:none;color:var(--text)">${c[1] || ''}</td><td contenteditable="true" style="outline:none;color:var(--text2)">${c[2] || ''}</td><td contenteditable="true" style="outline:none;color:var(--text2)">${c[3] || ''}</td><td><button class="del-btn" onclick="this.closest('tr').remove()">✕</button></td></tr>`; }
function _bDR(i, c) { return `<tr><td>DEP-${i}</td><td contenteditable="true" style="outline:none;color:var(--text2)">${c[1] || ''}</td><td><button class="del-btn" onclick="this.closest('tr').remove()">✕</button></td></tr>`; }

export function loadProject(input) {
    const file = input.files[0]; if (!file) return;
    const reader = new FileReader();
    reader.onload = ev => {
        let data; try { data = JSON.parse(ev.target.result); } catch { alert('Invalid file.'); input.value = ''; return; }
        if (!data._tc || !data._tc.startsWith('ThreatCanvas')) { if (!confirm('Not a ThreatCanvas file. Load anyway?')) { input.value = ''; return; } }
        const pi = data.projectInfo || {};
        ['appName', 'appVersion', 'appDesc', 'docOwner', 'docParticipants', 'docReviewer', 'docDate'].forEach(id => { const el = document.getElementById(id); if (el && pi[id] !== undefined) el.value = pi[id]; });
        const st = data.scopeTables || {};
        [['trustTbody', 'trust', _bTR], ['entryTbody', 'entry', _bER], ['exitTbody', 'exit', _bXR], ['assetsTbody', 'assets', _bAR], ['depsTbody', 'deps', _bDR]].forEach(([tbId, key, builder]) => {
            const tbody = document.getElementById(tbId); tbody.innerHTML = ''; ROW_COUNTS[key] = 0;
            (st[key] || []).forEach(cols => { ROW_COUNTS[key]++; tbody.insertAdjacentHTML('beforeend', builder(ROW_COUNTS[key], cols)); });
        });
        clearCanvas();
        const topo = data.topology || {};
        S.nodes = topo.nodes || {}; S.edges = (topo.edges || []).map(e => ({ ...e, _atk: false, _atkColor: null })); S.nextId = topo.nextId || 1;
        S.cmRows = data.cmRows || {};
        Object.values(S.nodes).forEach(nd => {
            const def = DEFS[nd.type]; if (!def) return;
            if (!nd.trustZone) { const _ztz = { public: 'internet', dmz: 'dmz', private: 'internal', isolated: 'restricted' }; nd.trustZone = def.trustZone || _ztz[nd.zone || 'private'] || 'internal'; }
            const el = document.createElement('div'); el.className = 'node'; el.id = nd.id; el.style.left = nd.x + 'px'; el.style.top = nd.y + 'px';
            el.innerHTML = `<div class="node-hdr" style="background:${def.color}18"><span class="node-ico"></span><span class="node-title" style="color:${def.color}"></span></div><div class="node-body"><span class="node-body-text"></span><br><span style="color:var(--text3);font-size:9px"></span></div><div class="node-pills" id="pills-${nd.id}"></div><div class="port port-r" data-node="${nd.id}"></div><div class="port port-l" data-node="${nd.id}"></div>`;
            el.querySelector('.node-ico').textContent = def.icon; el.querySelector('.node-title').textContent = nd.label; el.querySelector('.node-body-text').textContent = def.body; el.querySelectorAll('.node-body span')[1].textContent = nd.trust.toUpperCase();
            el.querySelectorAll('.port').forEach(p => p.addEventListener('mousedown', ev => { ev.stopPropagation(); handlePort(nd.id, p); }));
            let _lx, _ly; el.addEventListener('mousedown', ev => { if (ev.target.classList.contains('port')) return; _lx = ev.clientX; _ly = ev.clientY; });
            el.addEventListener('mouseup', ev => { if (ev.target.classList.contains('port')) return; if (Math.abs(ev.clientX - _lx) < 5 && Math.abs(ev.clientY - _ly) < 5) selNode(nd.id); });
            makeDrag(el, S.nodes[nd.id]); el.classList.add('tz-' + (nd.trustZone || 'internal') + '-node');
            document.getElementById('canvas').appendChild(el);
        });
        redraw(); upHint(S.nodes); goStep(2);
        setTimeout(() => { runAnalysis(); zoomFit(); setTimeout(renderTrustZoneOverlays, 150); document.getElementById('statusBar').textContent = `Project loaded — ${S.threats.length} threats detected`; }, 250);
        input.value = '';
    };
    reader.readAsText(file);
}

export function loadExample() {
    document.getElementById('appName').value = 'College Library Website'; document.getElementById('appVersion').value = '1.0';
    document.getElementById('appDesc').value = 'Online portal for students, faculty, and librarians to search, request, and manage books.';
    document.getElementById('docOwner').value = 'David Lowry'; document.getElementById('docParticipants').value = 'David Rook';
    document.getElementById('docReviewer').value = 'Eoin Keary'; document.getElementById('docDate').value = '2026-02-18';
    // Trust levels
    document.getElementById('trustTbody').innerHTML = ''; ROW_COUNTS.trust = 0;
    [['Anonymous Web User', 'No authentication'], ['Student / Staff', 'Valid login credentials'], ['Librarian', 'Admin, view PII'], ['DB Administrator', 'Full DB access'], ['Web Server Process', 'App code execution']].forEach(([n, d]) => { ROW_COUNTS.trust++; document.getElementById('trustTbody').insertAdjacentHTML('beforeend', `<tr><td>TL-${ROW_COUNTS.trust}</td><td contenteditable="true" style="outline:none;color:var(--text)">${n}</td><td contenteditable="true" style="outline:none;color:var(--text2)">${d}</td><td><button class="del-btn" onclick="this.closest('tr').remove()">✕</button></td></tr>`); });
    // Entry points
    document.getElementById('entryTbody').innerHTML = ''; ROW_COUNTS.entry = 0;
    [['HTTPS Port', 'All pages over TLS', 'TL-1, TL-2, TL-3'], ['Main Library Page', 'Splash page', 'TL-1'], ['Login Page', 'Auth form', 'TL-1, TL-2, TL-3'], ['Search Page', 'Book search', 'TL-2, TL-3']].forEach(([n, d, t]) => { ROW_COUNTS.entry++; document.getElementById('entryTbody').insertAdjacentHTML('beforeend', `<tr><td>EP-${ROW_COUNTS.entry}</td><td contenteditable="true" style="outline:none;color:var(--text)">${n}</td><td contenteditable="true" style="outline:none;color:var(--text2)">${d}</td><td contenteditable="true" style="outline:none;color:var(--text2)">${t}</td><td><button class="del-btn" onclick="this.closest('tr').remove()">✕</button></td></tr>`); });
    // Exit points
    document.getElementById('exitTbody').innerHTML = ''; ROW_COUNTS.exit = 0;
    [['Login Error Messages', 'May reveal valid usernames', 'High'], ['Search Results', 'XSS if not sanitised', 'Medium'], ['SQL Error Output', 'Exposes schema', 'High']].forEach(([n, d, r]) => { ROW_COUNTS.exit++; document.getElementById('exitTbody').insertAdjacentHTML('beforeend', `<tr><td>XP-${ROW_COUNTS.exit}</td><td contenteditable="true" style="outline:none;color:var(--text)">${n}</td><td contenteditable="true" style="outline:none;color:var(--text2)">${d}</td><td><select style="background:var(--s2);border:1px solid var(--border);border-radius:4px;color:var(--text);font-size:11px;padding:2px"><option ${r === 'High' ? 'selected' : ''}>High</option><option ${r === 'Medium' ? 'selected' : ''}>Medium</option><option ${r === 'Low' ? 'selected' : ''}>Low</option></select></td><td><button class="del-btn" onclick="this.closest('tr').remove()">✕</button></td></tr>`); });
    // Assets
    document.getElementById('assetsTbody').innerHTML = ''; ROW_COUNTS.assets = 0;
    [['User Login Credentials', 'Passwords in DB', 'TL-2, TL-4, TL-5'], ['Personal Data (PII)', 'Student info', 'TL-3, TL-4'], ['Library Availability', '24/7 uptime', 'TL-4, TL-5'], ['Audit Log Data', 'User ops trail', 'TL-3']].forEach(([n, d, t]) => { ROW_COUNTS.assets++; document.getElementById('assetsTbody').insertAdjacentHTML('beforeend', `<tr><td>A-${ROW_COUNTS.assets}</td><td contenteditable="true" style="outline:none;color:var(--text)">${n}</td><td contenteditable="true" style="outline:none;color:var(--text2)">${d}</td><td contenteditable="true" style="outline:none;color:var(--text2)">${t}</td><td><button class="del-btn" onclick="this.closest('tr').remove()">✕</button></td></tr>`); });
    // External deps
    document.getElementById('depsTbody').innerHTML = ''; ROW_COUNTS.deps = 0;
    [['Apache on hardened Linux'], ['MySQL on hardened Linux — private network'], ['Web-to-DB over private network'], ['Perimeter firewall — TLS only']].forEach(([d]) => { ROW_COUNTS.deps++; document.getElementById('depsTbody').insertAdjacentHTML('beforeend', `<tr><td>DEP-${ROW_COUNTS.deps}</td><td contenteditable="true" style="outline:none;color:var(--text2)">${d}</td><td><button class="del-btn" onclick="this.closest('tr').remove()">✕</button></td></tr>`); });
    // Build DFD
    goStep(2); clearCanvas();
    const ids = [];
    [{ t: 'user', x: 20, y: 130 }, { t: 'internet', x: 20, y: 275 }, { t: 'attacker', x: 20, y: 405 }, { t: 'waf', x: 284, y: 185 }, { t: 'loadbalancer', x: 284, y: 320 }, { t: 'webserver', x: 548, y: 80 }, { t: 'api', x: 548, y: 235 }, { t: 'database', x: 812, y: 155 }, { t: 'cache', x: 812, y: 305 }, { t: 'storage', x: 812, y: 28 }, { t: 'idp', x: 548, y: 385 }, { t: 'siem', x: 548, y: 480 }].forEach(n => ids.push(createNode(n.t, n.x, n.y)));
    const [uId, iId, aId, wId, lbId, wsId, apiId, dbId, cId, stId, idpId, siemId] = ids;
    [[uId, wId, 'HTTPS', 'Internal', 'JWT', 'TLS 1.3', 'No'], [iId, wId, 'HTTPS', 'Public', 'None', 'TLS 1.2 (strong)', 'Yes — Internet to DMZ'], [aId, wId, 'HTTP', 'Internal', 'None', 'None', 'Yes — Internet to DMZ'], [wId, lbId, 'HTTPS', 'Internal', 'API Key', 'TLS 1.3', 'No'], [lbId, wsId, 'HTTP', 'Internal', 'None', 'None', 'No'], [lbId, apiId, 'HTTPS', 'Confidential', 'JWT', 'TLS 1.3', 'No'], [wsId, stId, 'S3', 'Confidential', 'IAM Role', 'TLS 1.3', 'Yes — Internal to Restricted'], [apiId, dbId, 'SQL', 'PII', 'None', 'None', 'Yes — Internal to Restricted'], [apiId, cId, 'Redis', 'Confidential', 'None', 'TLS 1.2 (strong)', 'No'], [apiId, idpId, 'HTTPS', 'Confidential', 'OAuth2', 'TLS 1.3', 'No'], [wsId, siemId, 'TCP', 'Internal', 'API Key', 'TLS 1.2 (strong)', 'No'], [apiId, siemId, 'TCP', 'Internal', 'API Key', 'TLS 1.2 (strong)', 'No']].forEach(([from, to, p, d, a, e, tb]) => S.edges.push({ id: 'e' + S.nextId++, from, to, protocol: p, dataClass: d, auth: a, encryption: e, trustBoundary: tb, _atk: false, _atkColor: null }));
    redraw(); upHint(S.nodes);
    setTimeout(() => { runAnalysis(); requestAnimationFrame(() => requestAnimationFrame(() => { zoomFit(); setTimeout(renderTrustZoneOverlays, 150); })); }, 250);
}
