export const DEFS = {
    internet: { label: 'Internet', icon: '🌐', color: '#ff6b6b', body: 'External Network', trust: 'untrusted', zone: 'public', trustZone: 'internet', iamPriv: 'none' },
    user: { label: 'User', icon: '👤', color: '#4d9de0', body: 'Client / Browser', trust: 'untrusted', zone: 'public', trustZone: 'internet', iamPriv: 'none' },
    attacker: { label: 'Attacker', icon: '☠️', color: '#ff4444', body: 'Threat Actor', trust: 'hostile', zone: 'public', trustZone: 'internet', iamPriv: 'none' },
    firewall: { label: 'Firewall', icon: '🔥', color: '#ff8c00', body: 'Rules Engine', trust: 'trusted', zone: 'dmz', trustZone: 'dmz', iamPriv: 'none', isDetector: true },
    loadbalancer: { label: 'Load Balancer', icon: '⚖️', color: '#f59e0b', body: 'L7 LB', trust: 'trusted', zone: 'dmz', trustZone: 'dmz', iamPriv: 'none' },
    vpn: { label: 'VPN Gateway', icon: '🔒', color: '#4d9de0', body: 'Encrypted Tunnel', trust: 'trusted', zone: 'dmz', trustZone: 'dmz', iamPriv: 'none' },
    cdn: { label: 'CDN', icon: '☁️', color: '#60a5fa', body: 'Edge Cache', trust: 'trusted', zone: 'public', trustZone: 'internet', iamPriv: 'none' },
    webserver: { label: 'Web Server', icon: '🖥', color: '#0066ff', body: 'nginx / Apache', trust: 'internal', zone: 'private', trustZone: 'internal', iamPriv: 'standard' },
    api: { label: 'API Server', icon: '⚡', color: '#f59e0b', body: 'REST / GraphQL', trust: 'internal', zone: 'private', trustZone: 'internal', iamPriv: 'standard' },
    microservice: { label: 'Microservice', icon: '🔧', color: '#4d9de0', body: 'Service Mesh', trust: 'internal', zone: 'private', trustZone: 'internal', iamPriv: 'standard' },
    lambda: { label: 'Serverless', icon: 'λ', color: '#ff8c00', body: 'FaaS', trust: 'internal', zone: 'private', trustZone: 'internal', iamPriv: 'standard' },
    database: { label: 'Database', icon: '🗄', color: '#ff6b6b', body: 'PostgreSQL/MySQL', trust: 'restricted', zone: 'isolated', trustZone: 'restricted', iamPriv: 'none' },
    cache: { label: 'Cache', icon: '⚡', color: '#ffd93d', body: 'Redis/Memcached', trust: 'restricted', zone: 'isolated', trustZone: 'restricted', iamPriv: 'none' },
    storage: { label: 'Object Storage', icon: '📦', color: '#60a5fa', body: 'S3 / GCS', trust: 'restricted', zone: 'isolated', trustZone: 'restricted', iamPriv: 'none' },
    messagequeue: { label: 'Message Queue', icon: '📨', color: '#4d9de0', body: 'Kafka/RabbitMQ', trust: 'internal', zone: 'private', trustZone: 'internal', iamPriv: 'none' },
    waf: { label: 'WAF', icon: '🛡', color: '#ff8c00', body: 'Web App Firewall', trust: 'trusted', zone: 'dmz', trustZone: 'dmz', iamPriv: 'none', isDetector: true },
    idp: { label: 'Identity Provider', icon: '🔑', color: '#f59e0b', body: 'OAuth2/SAML', trust: 'trusted', zone: 'private', trustZone: 'internal', iamPriv: 'none' },
    siem: { label: 'SIEM', icon: '👁', color: '#ff4444', body: 'Log Analytics', trust: 'trusted', zone: 'private', trustZone: 'internal', iamPriv: 'none', isDetector: true },
};
